### ISSUE TITLE
Problem using gnoga with Alire

### ISSUE THREAD

**Issue by bracke** [Blady-Com/gnoga#10]
There is a problem when trying to add gnoga to a alr proejct.

```sh
alr init --bin mytestapp
cd mytestapp
alr build
--> builds successfull

alr with gnoga
alr build
-->
error: Trying to set an already defined environment variable:
error: Target_OS is already defined as 'Linux' but new value is 'auto'
```

I have reported this to thew Alire project https://github.com/alire-project/alire/issues/1687 but apparently it is a problem with Gnoga:

> Thanks for the report. This is indeed a mistake in the metadata of both `gnoga` and `simple_components`, that should not set these variables.

**Comment by Blady-Com** [comment]
Alire support for Gnoga is actually in an exploring access mode as building app processes are different.
With Gnoga you create your app inside Gnoga file structure.
With Alire you create your app in its own file structure using components.
That being said, I'm interested to know how you build you app in order to make relevant changes.
Could you share your project?
In the mean time, I suggest to follow the proposal of [mosteo](https://github.com/mosteo), at your project root do:
`% alr pin simple_components=4.62.0`
and then
`% alr build`
should be ok.

**Comment by bracke** [comment]
@Blady-Com  
> Could you share your project?:

I*m just experimenting, so I literally just did what I mentioned in the issue description:

alr init --bin mytestapp
cd mytestapp
alr build
--> builds successfull

alr with gnoga
alr build
-->
error: Trying to set an already defined environment variable:
error: Target_OS is already defined as 'Linux' but new value is 'auto'


I will try with the pin.

**Comment by mosteo** [comment]
I will fix this one in the Alire index directly.

**Comment by mosteo** [comment]
Fixed in https://github.com/alire-project/alire-index/pull/1082

**Comment by bracke** [comment]
@mostea 
Should it work now? 
I have tried alr index --update-all and then repeated the above but the result is the same.

**Comment by mosteo** [comment]
Sorry, it was not yet merged. Please try it now.

**Comment by bracke** [comment]
@mosteo I can confirm it works now.
Thank you for the quick response.
